import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import './styles/globals.scss';

const oswald = Oswald({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${oswald.className}`}>
      <body>{children}</body>
    </html>
  );
}
